### ISSUE TITLE
Unable to access jarfile spoon.jar

### ISSUE THREAD

**Issue by dmc1778** [SpoonLabs/metamutator#14]
When I try to create a meta mutator (step 1 of library usage), it tells that:

> Unable to access jarfile spoon.jar

I can't see any spoon.jar in the source of the project. Please help to fix this issue @monperrus

**Comment by monperrus** [comment]
thanks for the bug report. see updated documentation in 277dd39

**Comment by dmc1778** [comment]
Thanks, Dr.Monperrus.

I executed "mvn package" command and it gave the following error while
building the package:

[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on
project metamutator: There are test failures.

Then, I used this command "mvn install -DskipTests", and it built
successfully. However, in the target folder there are two jar files as :

1) metamutator-0.1-SNAPSHOT.jar
2) metamutator-0.1-SNAPSHOT-jar-with-dependencies.jar

There isn't any file named "metamutator-*-jar-with-dependencies.jar".

Thanks,

Nima.

**Comment by monperrus** [comment]
Thanks for the follow up. I suggest you learn about the Unix/Linux command line (aka shell) to
understand the meaning of `*`.

**Comment by dmc1778** [comment]
Thanks for your reply and suggestion Dr.Monperrus.

After running "*mvn package*" command in the command prompt, i see two
files generated as:

1) metamutator-0.1-SNAPSHOT.jar
2) metamutator-0.1-SNAPSHOT-jar-with-dependencies.jar

When I execute "*java -jar target/metamutator-*-jar-with-dependencies.jar
-i src/main/java -p metamutator.LogicalExpressionMetaMutator -o spooned*"
command, the cmd says:

>>Error: Unable to access jarfile
target/metamutator-*-jar-with-dependencies.jar

I was wondering if you tell me why I get this error?

Thanks for your assistance,

Regards,

Nima.

**Comment by monperrus** [comment]
FYI, the course for you: 

Unix Tools: Data, Software and Production Engineering
https://www.edx.org/course/unix-tools-data-software-and-production-engineering

Starts March 17.
