### ISSUE TITLE
No main manifest attribute

### ISSUE THREAD

**Issue by ljj430** [SpoonLabs/metamutator#16]
Hi! When I ran the command line to create the metaprogram, it showed "no main manifest attribute". Seems like there is no main class in pom.xml. Is there any help? Thanks.

**Comment by monperrus** [comment]
The main class is `spoon.Launcher`. Could you try with 

    java -cp target/metamutator-*-jar-with-dependencies.jar spoon.Launcher -i src/main/java -p metamutator.LogicalExpressionMetaMutator -o spooned

**Comment by junjieli-1997** [comment]
Thanks! I fixed it!
